name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: salesforce-agent
  PYTHON_VERSION: '3.9'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Setup Python Virtual Environment
      run: |
        VENV_PATH="${GITHUB_WORKSPACE}/venv"
        echo "Creating virtual environment at ${VENV_PATH}"
        python -m pip install --upgrade pip virtualenv
        python -m virtualenv "${VENV_PATH}"
        source "${VENV_PATH}/bin/activate"
        python --version
        pip --version

    - name: Install dependencies
      run: |
        source "${GITHUB_WORKSPACE}/venv/bin/activate"
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gunicorn

    - name: Create deployment package
      run: |
        source "${GITHUB_WORKSPACE}/venv/bin/activate"
        echo "Installing production dependencies..."
        pip freeze > requirements.txt
        
        echo "Creating deployment package..."
        zip -r deployment.zip . \
          -x "*.git*" \
          -x "*.github*" \
          -x "*.pytest_cache*" \
          -x "__pycache__/*" \
          -x "*.pyc" \
          -x "*.env*" \
          -x "*.vscode*" \
          -x "*.idea*" \
          -x "venv/*"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deployment.zip

    - name: Post Deployment Status
      run: |
        echo "Deployment completed successfully!"
        echo "Your app should be available at: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net" 